"""Core reference checking logic."""

import os
import re
from collections.abc import Iterable
from collections.abc import Iterator
from pathlib import Path

from .config import Config
from .output import CheckType
from .output import Issue
from .output import Unreadable
from .output import Warning
from .rules import load_rules
from .suggestions import FileSuggestions


class ReferenceChecker:
    """Validates file references across a codebase."""

    DEFAULT_EXCLUDES = {
        '.git',
        'node_modules',
        '.venv',
        'site',
        '__pycache__',
        '.cache',
        # Tool caches record what a path *was* on the last run, same as the
        # append-only logs excluded below. .pytest_cache/v/cache/nodeids holds a
        # node ID per collected test, so renaming a test package reported twenty
        # misses against a file regenerated by the next pytest run.
        '.pytest_cache',
        '.ruff_cache',
        '.mypy_cache',
    }

    DEFAULT_EXCLUDE_PATTERNS = [
        '*.pyc',
        '.claude/metrics/**',
        '.planning/**',
        'site/**',
        # Append-only event logs record what a path *was*, not what should
        # exist. A 197 MB devstats log naming every file a hook once checked
        # reported nine misses for one query, all of them history.
        '*.jsonl',
        # Same reasoning: a run transcript names what existed when it ran. A
        # gitignored test-wsl-docker.log reported the pre-rename name of a tool
        # that had just been renamed everywhere it is actually referenced.
        '*.log',
        # A changelog is that same thing written deliberately: an entry naming
        # cli/Makefile is correct precisely because that is where the file was
        # when it shipped, and rewriting history to match the current tree would
        # be the bug. Seven of the twenty-two hits in the fleet-wide rename
        # replay were changelog entries, the single largest source of noise.
        'CHANGELOG.md',
    ]

    # A fixtures directory holds recorded data, not references. ichrisbirch's
    # tests/stats/fixtures/tool_outputs/tokei_output.json is a captured tokei
    # run naming every file in the repo when it was taken, and one commit
    # removing the Flask app made it 219 of the 280 hits across the whole fleet
    # — enough to bury the four findings that were real. Nobody would hand-edit
    # it either; the fix is to re-run the tool. `--test-mode` scans them anyway.
    TEST_FIXTURE_PATTERNS = [
        'tests/apps/test-refcheck.sh',
        'fixtures/**',
        '**/fixtures/**',
        'testdata/**',
        '**/testdata/**',
        'docs/archive/**',
    ]

    # A command handed to one of these runs on another host or inside a
    # container, so its paths describe a filesystem this process cannot see.
    # Same reasoning as DYNAMIC_PATH_PATTERNS: not a broken reference, just not
    # ours to resolve.
    REMOTE_EXECUTION_PATTERNS = [
        r'\bpct\s+exec\b',
        r'\blxc\s+exec\b',
        r'\bdocker\s+exec\b',
        r'\bkubectl\s+exec\b',
        r'\bssh\s+\S+',
        r'\bsu\s+-\s*\S*\s+-c\b',
    ]

    DYNAMIC_PATH_PATTERNS = [
        r'^\$',
        r'^/tmp/',
        r'^/root/',
        r'^/home/',
        r'^/Users/',
        # Same class as the home directories above: machine state, not repo
        # content. Whether /etc/os-release resolves says which OS is running the
        # check, so a Mac would report the `. /etc/os-release` that theme and
        # font each run behind a Linux guard.
        r'^/etc/',
        r'/nvm\.sh$',
        r'^/lib/lib\.sh',
    ]

    # A line whose command emits text is showing an invocation, not making one.
    # Matched at the start of the line rather than anywhere in it, for the same
    # reason the source and script lookbehinds exist: `bash setup.sh && echo ok`
    # runs the script, and only the leading command says what the line is for.
    DOCUMENTING_COMMANDS = re.compile(r'^\s*(?:echo|printf)\b')

    # A fenced block opens on three or more backticks or tildes and may name the
    # language it holds. Only the first word of that info string is the
    # language, because ```bash file=scripts/deploy.sh carries an attribute
    # after it.
    FENCE_DELIMITER = re.compile(r'^\s*(`{3,}|~{3,})\s*(\S*)')

    # The info strings that mean a block holds shell. `console` and
    # `shellsession` are the two spellings markdown uses for a transcript, and
    # a transcript is exactly where a documented invocation lives.
    SHELL_FENCE_LANGUAGES = frozenset(
        {
            'bash',
            'sh',
            'shell',
            'shellsession',
            'shell-session',
            'console',
            'zsh',
            'ksh',
        }
    )

    # An argument ends on a path character so prose punctuation stays out of the
    # filename: `source lib/setup.sh, then run it` has to yield lib/setup.sh and
    # not lib/setup.sh,. check_script_references gets that for free by anchoring
    # on the `.sh` suffix, which a sourced file need not carry.
    SOURCE_ARGUMENT = r'(?:["\']([^"\']+)["\']|([^\s"\'`;&|()<>]*[\w/}~]))'

    # Where a `.` can be the source builtin rather than a full stop: opening a
    # line, following a separator, or following a keyword that opens a command.
    # Accepting a preceding space instead would read `find . lib/` as sourcing
    # lib/, and English never puts a space before a full stop.
    COMMAND_POSITION = r'(?:^|[;&|({]|\b(?:then|else|do)\b)'

    # Both ways a shell reads a file into itself. The `source` lookbehind keeps
    # the tail of a longer word out: `resource "aws_lambda_function"` in a
    # Terraform block reported a missing file named after the resource, and
    # newsboat's `urls-source "freshrss"` did the same.
    SOURCE_COMMAND = re.compile(rf'(?<![\w-])source\s+{SOURCE_ARGUMENT}|{COMMAND_POSITION}\s*\.\s+{SOURCE_ARGUMENT}')

    # Quotes already say the token is an argument; a bare word may just be the
    # next word of a sentence, so it has to look like a path before it is
    # resolved. "the source of truth" and "we do . nothing" both die here.
    PATH_SHAPED_ARGUMENT = re.compile(r'/|\.(?:sh|bash|zsh)$')

    # A doc that explains how to add an installer writes
    # `install/common/github-releases/toolname.sh`, and the file is never meant
    # to exist. Reporting a stand-in is the kind of noise that teaches a reader
    # to skim past the real findings underneath it, so these are matched on the
    # basename only — a genuine path under a templated directory still resolves
    # and still gets reported when it goes stale.
    PLACEHOLDER_BRACES = re.compile(r'[{<][^}>]*[}>]')

    PLACEHOLDER_STEMS = {
        'tool',
        'toolname',
        'tool-name',
        'script',
        'scriptname',
        'script-name',
        'installer-script',
        'filename',
        'example',
        'placeholder',
        'foo',
        'bar',
        'baz',
    }

    PLACEHOLDER_PREFIXES = ('my-', 'my_', 'your-', 'your_', 'example-', 'example_')

    def __init__(
        self,
        root_dir: Path | None = None,
        search_path: Path | None = None,
        skip_docs: bool = False,
        file_type: str | None = None,
        warn_fragile: bool = True,
        strict: bool = False,
        test_mode: bool = False,
        config: Config | None = None,
    ):
        self.root_dir = root_dir or Path.cwd()

        # The same root with its symlinks walked out, for comparing against
        # other repos' homes. root_dir itself stays as given, because every
        # file this walk yields is built from it and relative_to would stop
        # matching. Only the cross-repo containment check uses this one.
        self.physical_root = Path(os.path.realpath(self.root_dir))

        self.search_path = search_path or self.root_dir
        self.skip_docs = skip_docs
        self.file_type = file_type
        self.warn_fragile = warn_fragile
        self.strict = strict
        self.test_mode = test_mode
        self.config = config or Config()
        self.issues: list[Issue] = []
        self.warnings: list[Warning] = []
        self.unreadable: list[Unreadable] = []
        self.exclude_dirs = self.DEFAULT_EXCLUDES.copy()
        self.exclude_patterns = self.DEFAULT_EXCLUDE_PATTERNS.copy()
        self._rules: dict | None = None
        self._rules_path: Path | None = None

        if not test_mode:
            self.exclude_patterns.extend(self.TEST_FIXTURE_PATTERNS)

        # The patterns above are the ones true of any repository. Which of a
        # repo's own directories hold generated output is a fact only that repo
        # knows, so it declares them and they arrive here through the config.
        self.exclude_patterns.extend(self.config.exclude)

        self._suggestions = FileSuggestions(self.root_dir, self.exclude_dirs, self.exclude_patterns)

    def should_skip_file(self, file_path: Path) -> bool:
        """Determine if file should be skipped."""
        return self._suggestions.should_skip_file(file_path)

    def is_dynamic_path(self, path: str) -> bool:
        """Check if path is dynamic/runtime-generated."""
        return any(re.search(pattern, path) for pattern in self.DYNAMIC_PATH_PATTERNS)

    def runs_on_another_host(self, line: str) -> bool:
        """Check if the line hands its command to a remote or container executor."""
        return any(re.search(pattern, line) for pattern in self.REMOTE_EXECUTION_PATTERNS)

    def documents_rather_than_runs(self, line: str, file_path: Path) -> bool:
        """Whether this occurrence is showing a command rather than issuing one.

        Markdown is documentation throughout. A shell script is documentation in
        the two places it explains itself: a `#` comment, and a usage string it
        echoes. logsift's header block writes `bash install.sh` as an
        illustration and `bash management/run-and-summarize.sh` under a
        "CORRECT:" heading, then echoes both back from its usage function — and
        that one file produced seven reported misses, none of them a reference to
        anything.

        This chooses which guards apply, never whether the line is read. A
        comment naming a directory the repo has still resolves and is still
        reported, which is the drift the comment at check_relative_path_fragility
        was careful to keep scanning for.
        """
        return file_path.suffix == '.md' or line.lstrip().startswith('#') or bool(self.DOCUMENTING_COMMANDS.match(line))

    def fence_reads_as_shell(self, info: str) -> bool:
        """Whether a fence's info string says the block holds shell.

        An empty info string is shell here. An untagged block is very commonly
        shell, and prose is where a stale reference survives longest, so an
        explicit tag naming another language is the only thing that puts a block
        out of scope.
        """
        language = info.strip('{}.').lower()
        return not language or language in self.SHELL_FENCE_LANGUAGES

    def lines_a_shell_could_run(self, file_path: Path, lines: Iterable[str]) -> Iterator[tuple[int, str]]:
        """The numbered lines of a file, less the fenced blocks holding another language.

        Markdown quotes other languages constantly, and a tool's own output is
        the case that bites hardest. A ```yaml block showing a sample report
        prints `bash tests/helpers.sh` as a finding; `tests/` is a directory the
        repo really has, so the leading-directory guard passes it through and
        refcheck reports itself. Nothing downstream can tell that line from an
        invocation, because by the time it arrives it is identical to one.

        The fence markers never come back either. ```bash file=scripts/deploy.sh
        opens a block rather than running anything, and its attributes parse as
        an invocation of a file named `file=scripts/deploy.sh`.

        Fences are a markdown construct, so every line of any other file is
        yielded as it is read.
        """
        if file_path.suffix != '.md':
            yield from enumerate(lines, 1)
            return

        fence = ''
        holds_shell = False

        for line_num, line in enumerate(lines, 1):
            if fence:
                # A closing run is the same character as the opener and at least
                # as long, which is what lets a ``` block sit inside a ````
                # block without ending it.
                closer = line.strip()
                if len(closer) >= len(fence) and set(closer) == {fence[0]}:
                    fence = ''
                elif holds_shell:
                    yield line_num, line
                continue

            opener = self.FENCE_DELIMITER.match(line)
            if opener:
                fence = opener.group(1)
                holds_shell = self.fence_reads_as_shell(opener.group(2))
                continue

            yield line_num, line

    def anchor(self, path: str) -> Path:
        """Where a referenced path actually lives, absolute.

        Three anchors, not two. An absolute path is itself and a bare one hangs
        off the repo — but a `~/` path hangs off the *home directory*, and joining
        it to the repo root produces `<repo>/~/…`, which cannot exist for any
        input. Every tilde reference was therefore reported missing, always.

        Measured on dotfiles: `tests/apps/all-apps.sh` sources three deployed
        shell libraries by their `~/.local/shell/` paths, and all three were
        reported on every run while resolving fine. That is the whole of this
        tool's value spent on noise — a checker is worth its false-positive rate,
        and three standing errors is what teaches a reader to stop reading the
        output.

        A `~/` reference is the *deployed* spelling, which is the one a script
        that runs outside the repo has to use. It is not a variant of a repo-
        relative path and cannot be rewritten into one.
        """
        if path.startswith('~'):
            return Path(path).expanduser()
        if path.startswith('/'):
            return Path(path)
        return self.root_dir / path

    def describes_another_tree(self, path: str) -> bool:
        """Check if a documented path belongs to some project other than this one.

        Documentation quotes other people's trees constantly — a guide to a test
        framework writes `./test/mylib_test.sh`, one explaining `set -e` writes
        `source child.sh`. Neither is a claim about this repo, and reporting
        them buries the references that are.

        The discriminator is the leading directory. A stale reference to our own
        code still names a directory we have, which is what makes the rename
        case work: `tests/install/utils/verify.sh` is reported because `tests/`
        exists, even though `utils/` has since become `verification/`. A bare
        filename anchors to nothing and is always illustrative.

        Callers gate this on documents_rather_than_runs: in code the same bare
        filename is a real invocation that has to resolve.
        """
        # $DOTFILES_DIR is already resolved to an absolute path by this point,
        # and it is repo-rooted by construction — judge it on the part below the
        # root, not on the leading slash.
        candidate = path
        if path.startswith('/'):
            try:
                candidate = str(Path(path).relative_to(self.root_dir))
            except ValueError:
                return True

        head = candidate.split('/', 1)[0]
        if head in ('', '.', '..', '~'):
            return True

        return not (self.root_dir / head).is_dir()

    def names_a_placeholder(self, path: str) -> bool:
        """Check if a documented reference is a stand-in, not a path meant to exist.

        Documentation only, which callers gate on. `bash script.sh` as a line of
        code is a real invocation and has to resolve; the identical line in a
        README, or in the comment above the function, is a stand-in for whatever
        the reader is writing. Applying the stem list to code would stop
        reporting genuine misses in any repo that happened to ship a `tool.sh`.
        """
        basename = path.rsplit('/', 1)[-1]
        if self.PLACEHOLDER_BRACES.search(basename):
            return True
        stem = basename.rsplit('.', 1)[0].lower()
        return stem in self.PLACEHOLDER_STEMS or stem.startswith(self.PLACEHOLDER_PREFIXES)

    def load_rules(self) -> dict:
        """Load rules from config directory."""
        if self._rules is not None:
            return self._rules
        self._rules, self._rules_path = load_rules(self.root_dir)
        return self._rules

    def find_similar_files(self, missing_path: str) -> list[str]:
        """Find files that might be renamed versions of missing_path."""
        rules = self.load_rules()
        return self._suggestions.find_similar_files(missing_path, rules)

    def reference_check_files(self) -> list[Path]:
        """Files whose source/script references get validated.

        Markdown is in because a usage example naming a library is exactly the
        drift this tool exists to catch, and for a long time it was scanned by
        nothing: these checks globbed `**/*.sh`, so `refcheck docs/` reported
        "all references valid" over five copies of
        `source "$DOTFILES_DIR/install/common/lib/error-handling.sh"` pointing
        at a path no code had used in months. A false clean is worse than a
        false positive, because it certifies the rot.

        Filtering one full listing rather than globbing per suffix is what makes
        a single-file argument behave: find_files ignores its pattern in that
        case and returns the file, so two globs returned it twice and scanned
        it twice, and --skip-docs could never exclude it.
        """
        suffixes = {'.sh'} if self.skip_docs else {'.sh', '.md'}
        return [f for f in self.find_files() if f.suffix in suffixes]

    def note_unreadable(self, path: Path, error: OSError) -> None:
        """Record a path the walk was handed and could not read.

        Every caller here sat behind a bare `continue`. A file that will not
        open is a file nobody scanned, and the run still printed a tick, so the
        one output the tool exists to produce was a claim about files it had
        never seen.

        Recorded once per path. A single run walks the tree four times — once
        for patterns, once for source and script statements, twice for the
        fragile-path warnings — so one refused directory arrives here four
        times and would print as four findings.
        """
        entry = Unreadable(path=path, reason=error.strerror or str(error))
        if entry not in self.unreadable:
            self.unreadable.append(entry)

    def find_files(self, suffix: str | None = None) -> list[Path]:
        """Every file under the search path, minus the exclusions.

        Walked rather than globbed because a glob has nowhere to report a
        directory it could not enter. `Path.glob` swallows the kernel's refusal
        and yields the entries it did reach, so an unreadable directory removed
        part of a repo from the scan and nothing said so. `os.walk` hands the
        error to `onerror`, which is the only reason the walk is written out.

        Sorted so two runs over the same tree report in the same order.
        """
        files: list[Path] = []
        search_root = self.search_path

        # Handle single file argument
        if search_root.is_file():
            if self.file_type and search_root.suffix != f'.{self.file_type}':
                return files
            try:
                rel_path = search_root.relative_to(self.root_dir)
            except ValueError:
                return files
            if not self.should_skip_file(rel_path):
                files.append(search_root)
            return files

        def refused(error: OSError) -> None:
            self.note_unreadable(Path(error.filename or search_root), error)

        for dirpath, _, filenames in os.walk(search_root, onerror=refused):
            for name in filenames:
                file_path = Path(dirpath) / name

                # A broken symlink lists as a file and is not one. glob dropped
                # it on the same question, so the walk has to ask it too.
                if not file_path.is_file():
                    continue

                try:
                    rel_path = file_path.relative_to(self.root_dir)
                except ValueError:
                    continue

                if self.should_skip_file(rel_path):
                    continue

                if suffix and file_path.suffix != suffix:
                    continue

                if self.file_type and file_path.suffix != f'.{self.file_type}':
                    continue

                files.append(file_path)

        return sorted(files)

    # Characters that can sit inside a path token in prose, a Dockerfile or a
    # CI file. Backticks, quotes and sentence punctuation are deliberately out,
    # so a markdown `path/like/this` yields the path and not the fence.
    PATH_TOKEN_CHARS = re.compile(r'[\w./~${}-]')

    # A leading `$VAR/` or `${VAR}/`, which is the only part of a path token that
    # cannot be resolved from here. What follows it is an ordinary relative path.
    VARIABLE_ROOT = re.compile(r'^\$\{?\w+\}?/')

    def _path_tokens_around(self, pattern: str, line: str) -> Iterator[tuple[str, bool]]:
        """Each hit on this line, widened to the whole path token holding it.

        Yields the token and whether the pattern begins it. A hit that begins
        its own token has no path in front of it, which the two callers read in
        opposite directions: in this repo that is a bare mention worth
        reporting, and in another repo it is a name that cannot reach here.

        `:` is not a path character, so widening stops right after a URL
        scheme's `//`. A hit inside a URL is never a file reference —
        `docs/claude-code` in docs.anthropic.com/en/docs/claude-code/hooks was
        reported as a moved path — so those hits are dropped rather than
        yielded.
        """
        start = 0
        while (index := line.find(pattern, start)) != -1:
            start = index + len(pattern)

            left = index
            while left > 0 and self.PATH_TOKEN_CHARS.match(line[left - 1]):
                left -= 1
            right = index + len(pattern)
            while right < len(line) and self.PATH_TOKEN_CHARS.match(line[right]):
                right += 1

            if left > 0 and line[left - 1] == ':':
                continue

            # Trailing only. A leading dot is part of the path — stripping both
            # ends turns `../a.json` into the absolute `/a.json` and `.github`
            # into a `github` that is not there, so both resolve to nothing.
            yield line[left:right].rstrip('.'), left == index

    @staticmethod
    def _on_this_filesystem(token: str) -> Path | None:
        """A path token as somewhere on this machine, or None when it is not one.

        `~` and the environment are expanded, and anything left holding a `$`
        named a variable this process does not carry. Only an absolute result
        is a real location: a relative token belongs to whichever repo the line
        sits in, and that is resolved against a root instead.

        The path comes back as written. It is what a program reading that line
        will open, so it is what the existence test has to be asked about —
        rewriting it first answers about a different file.
        """
        expanded = os.path.expandvars(os.path.expanduser(token))
        if '$' in expanded or not expanded.startswith('/'):
            return None
        return Path(expanded)

    def _pattern_hit_still_resolves(self, pattern: str, line: str, from_file: Path | None = None) -> bool:
        """True when every hit on this line sits inside a path that exists.

        `--pattern boards/arm` matched `config/boards/arm/...` after the
        directory moved under config/, reporting the file that had just been
        fixed. A substring match cannot tell a stale reference from a correct
        longer path that happens to end the same way, so resolve the whole
        token: if it is on disk it is not stale, and a genuinely moved path
        still fails to resolve and is still reported.

        A bare filename is resolved the same way, because a rename whose new
        name ends in the old one is the common case rather than the exotic one
        — `tools.json` to `fleet-built-tools.json` puts the pattern inside
        every site that was just repaired. A hit standing alone as its own
        token is still reported, so `--pattern backmeup` finds `Run backmeup`.

        `from_file` is the file the line came from, and a token is resolved
        against that file's directory as well as the root. A markdown link
        spells its target relative to itself, so `../pinned-versions.json` in
        standards/ resolves from there and nowhere else.

        A token naming somewhere absolute is tested against the filesystem
        rather than against a root. `~/.local/share/<repo>/pinned-versions.json`
        is a corrected reference and hangs off no root in this repo, so joining
        it to one reported the file that had just been fixed.
        """
        for token, begins_the_token in self._path_tokens_around(pattern, line):
            if begins_the_token or not token:
                return False

            # Tried first and never on its own. An absolute token needs nothing
            # here — joining it to a root discards the root — but `~` and a set
            # variable are literal text until expanded, so joining those to a
            # root builds a path that cannot exist and reports the file that was
            # just repaired. Falling through on a miss keeps the root-relative
            # candidates below, which answer for a variable pointing elsewhere.
            target = self._on_this_filesystem(token)
            if target is not None and target.exists():
                continue

            bases = [self.root_dir]
            if from_file is not None:
                bases.append(from_file.parent)

            # A token rooted at a shell variable has no literal path to test, and
            # `$REPO_ROOT/homelab-hosts.json` is the corrected reference rather
            # than a stale one. The variable is dropped and the remainder is
            # resolved, so a live name is found and `$REPO_ROOT/hosts.json` still
            # resolves to nothing and is still reported.
            candidates = [token, self.VARIABLE_ROOT.sub('', token, count=1)]
            if not any((base / candidate).exists() for base in bases for candidate in candidates if candidate):
                return False

        return True

    @staticmethod
    def _in_a_named_repo(token: str, repo_paths: dict[str, Path]) -> Path | None:
        """A `<repo-name>/path/inside/it` token as a location, or None.

        Prose reaches another repo by naming it. `documentation.md` § "A
        citation names a repo by its registry name" makes that the fleet's
        declared form, so `dotfiles/apps/common/pr-list` is what a standards
        file writes and a `~`-rooted path is what it does not. The registry
        supplies the mapping, which is what turns the first segment into a
        directory.

        A token carrying no `/` is a bare name and stays None. `dotfiles` alone
        in a sentence names a repo rather than a file in one, and resolving it
        to the repo root would answer about a directory that always exists.
        """
        head, slash, tail = token.partition('/')
        if not slash or not tail:
            return None
        home = repo_paths.get(head)
        return home / tail if home else None

    def _resolves_in_this_repo(self, token: str, from_file: Path | None) -> bool:
        """True when the token names something this repo actually holds.

        A registry name and an ordinary directory name collide — `docs`,
        `theme`, `font` and `work` are all repos and all common top-level
        directories. So a repo's own `docs/index.md` is asked about here first,
        and only a token this repo cannot answer for is handed to the repo its
        first segment names.
        """
        bases = [self.root_dir]
        if from_file is not None:
            bases.append(from_file.parent)
        return any((base / token).exists() for base in bases)

    def _reaches_a_gone_path_in(
        self,
        pattern: str,
        line: str,
        repo_homes: dict[Path, str],
        repo_paths: dict[str, Path],
        from_file: Path | None = None,
    ) -> str | None:
        """The repo a hit on this line names a missing file in, if it names one.

        A reference from one repo to another reaches it in one of two ways. It
        spells a location on this machine — an absolute path, `~`, or a variable
        holding one — or it names the repo and the path inside it, which is what
        prose does. Either way the existence test is exact instead of textual:
        resolve the token, and report it only when the path it names is inside a
        repo the caller listed and is not there.

        This is the whole defence against a basename sweeping 90 repos for
        `versions.json`. Every mention that is a filename literal, a fixture
        name or a sentence in prose fails the first half, and every corrected
        reference fails the second.

        The two halves ask about different forms of the same path, because they
        are answered by different authorities. Existence is the kernel's, so it
        gets the path as written — the one a program on that line would open.
        Containment is a string comparison, so it gets the path with its
        symlinks and `..` walked out. Handing either the other's form is a bug
        in whichever direction it is done: flattening before the existence test
        reports a file that is on disk, and comparing an unwalked path places a
        real file outside every repo that holds it.
        """
        for token, begins_the_token in self._path_tokens_around(pattern, line):
            if begins_the_token or not token:
                continue

            target = self._on_this_filesystem(token)
            if target is None:
                if self._resolves_in_this_repo(token, from_file):
                    continue
                target = self._in_a_named_repo(token, repo_paths)
            if target is None or target.exists():
                continue

            physical = Path(os.path.realpath(target))

            # Longest match wins, so a repo checked out inside another is
            # credited to the inner one rather than to whatever encloses it.
            for home in sorted(repo_homes, key=lambda home: len(home.parts), reverse=True):
                if home != self.physical_root and physical.is_relative_to(home):
                    return repo_homes[home]

        return None

    def check_pattern(self, pattern: str, description: str | None = None):
        """Check for old path pattern references."""
        self.check_patterns({pattern: description or f'Old pattern: {pattern}'})

    def check_patterns(self, patterns: dict[str, str]):
        """Check for several old paths in one walk of the tree.

        A commit that moves a directory stages a rename per file in it, and
        --moves turns each into a pattern. Walking once per pattern made the
        cost of the check scale with the size of the move, which is backwards:
        the large refactor is exactly the one worth checking.
        """

        def stale(pattern: str, line: str, from_file: Path) -> str | None:
            if self._pattern_hit_still_resolves(pattern, line, from_file):
                return None
            return f'Found: {pattern}'

        self._scan_for_patterns(patterns, stale)

    def check_patterns_across_repos(self, patterns: dict[str, str], repo_homes: dict[Path, str], repo_paths: dict[str, Path]):
        """Check this tree for paths that moved in one of the other repos.

        The renaming repo cannot see its consumers. Run with this repo as the
        root and the moved paths as patterns, and the consumer side of a rename
        is answerable — the file that names the old path is right here, and the
        old path is gone from the repo that holds it.

        The reporting rule is tighter than check_patterns, and it has to be. In
        the repo that did the moving, any surviving mention of the old name is
        suspect, because its own files are the ones that moved. In another repo
        the same string is usually that repo's own business, so only a path
        reaching into a listed repo counts.

        `repo_homes` answers which repo holds a resolved path and `repo_paths`
        answers where a named repo sits. Both are needed and neither is the
        other's inverse: a registry may declare one repo at a symlink and
        another at the directory it points to, so the physical key is not a name
        and the name is not a physical key.
        """

        def stale(pattern: str, line: str, from_file: Path) -> str | None:
            owner = self._reaches_a_gone_path_in(pattern, line, repo_homes, repo_paths, from_file)
            return f'Gone from {owner}: {pattern}' if owner else None

        self._scan_for_patterns(patterns, stale)

    def _scan_for_patterns(self, patterns: dict[str, str], stale) -> None:
        """One walk of the tree, asking `stale` of every hit it finds."""
        if not patterns:
            return

        for file_path in self.find_files():
            if self.skip_docs and file_path.suffix == '.md':
                continue

            if file_path.name in ('refcheck', 'verify-references.py', 'verify-file-references.sh'):
                continue

            try:
                rel_path = file_path.relative_to(self.root_dir)
                with file_path.open(encoding='utf-8', errors='ignore') as f:
                    for line_num, line in enumerate(f, 1):
                        for pattern, description in patterns.items():
                            if pattern not in line:
                                continue
                            message = stale(pattern, line, file_path)
                            if message:
                                self.issues.append(
                                    Issue(
                                        file=rel_path,
                                        line_num=line_num,
                                        check_type=CheckType.PATTERN,
                                        message=message,
                                        suggestion=description,
                                    )
                                )
            except OSError as error:
                self.note_unreadable(file_path, error)
                continue
            except UnicodeDecodeError:
                # Not a failure to read. The bytes arrived and are not text, so
                # there is no reference in them to miss, and reporting every
                # binary file is the noise that stops the real findings landing.
                continue

    def go_up_n_levels(self, file_path: Path, n: int) -> Path:
        """Go up N directory levels from file_path."""
        path = file_path.parent
        for _ in range(n - 1):
            path = path.parent
        return path

    def find_repo_root(self, file_path: Path) -> Path:
        """Find git repo root from file path."""
        current = file_path.parent
        while current != current.parent:
            if (current / '.git').exists():
                return current
            current = current.parent
        return self.root_dir

    def parse_variable_assignments(self, file_path: Path) -> dict[str, str]:
        """Parse common shell variable assignment patterns."""
        symbol_table: dict[str, str] = {}

        # Prose has no assignments to parse, but its $DOTFILES_DIR names the
        # same repo root every script's does, and without seeding it every
        # documented `source "$DOTFILES_DIR/..."` fails to resolve and is
        # skipped. $SCRIPT_DIR stays unresolved on purpose: in prose there is
        # no one script for it to be relative to, so guessing would invent
        # misses.
        if file_path.suffix == '.md':
            symbol_table['DOTFILES_DIR'] = str(self.find_repo_root(file_path))
            return symbol_table

        try:
            content = file_path.read_text(encoding='utf-8')
        except OSError as error:
            self.note_unreadable(file_path, error)
            return symbol_table
        except UnicodeDecodeError:
            return symbol_table

        if re.search(r'SCRIPT_DIR="\$\(cd.*BASH_SOURCE', content):
            symbol_table['SCRIPT_DIR'] = str(file_path.parent)

        match = re.search(r'DOTFILES_DIR="\$\(cd "\$SCRIPT_DIR/((?:\.\./?)+)" && pwd\)"', content)
        if match:
            relative_path = match.group(1)
            levels_up = relative_path.count('..')
            symbol_table['DOTFILES_DIR'] = str(self.go_up_n_levels(file_path, levels_up + 1))

        if re.search(r'DOTFILES_DIR="\$\{DOTFILES_DIR:-\$HOME/dotfiles\}"', content):
            symbol_table['DOTFILES_DIR'] = str(self.find_repo_root(file_path))

        return symbol_table

    def resolve_path(self, path_str: str, symbol_table: dict[str, str], file_path: Path) -> str:
        """Resolve a path containing shell variables."""
        resolved = path_str

        for var_name, var_value in symbol_table.items():
            resolved = resolved.replace(f'${var_name}', var_value)
            resolved = resolved.replace(f'${{{var_name}}}', var_value)

        if '$' in resolved:
            raise ValueError(f'Cannot resolve variables in: {path_str}')

        return resolved

    def check_source_statements(self):
        """Check that source statements point to existing files."""
        for file_path in self.reference_check_files():
            try:
                rel_path = file_path.relative_to(self.root_dir)
                symbol_table = self.parse_variable_assignments(file_path)

                with file_path.open(encoding='utf-8') as f:
                    for line_num, line in self.lines_a_shell_could_run(file_path, f):
                        match = self.SOURCE_COMMAND.search(line)
                        if not match:
                            continue

                        if self.runs_on_another_host(line):
                            continue

                        quoted, bare = match.group(1) or match.group(3), match.group(2) or match.group(4)
                        source_path = quoted or bare
                        if not source_path:
                            continue

                        if bare and not self.PATH_SHAPED_ARGUMENT.search(bare):
                            continue

                        if '$' not in source_path and self.is_dynamic_path(source_path):
                            continue

                        documentation = self.documents_rather_than_runs(line, file_path)

                        if documentation and self.names_a_placeholder(source_path):
                            continue

                        original_path = source_path
                        if '$' in source_path:
                            try:
                                source_path = self.resolve_path(source_path, symbol_table, file_path)
                            except ValueError:
                                continue

                        if documentation and self.describes_another_tree(source_path):
                            continue

                        resolved = self.anchor(source_path)

                        if not resolved.exists():
                            similar = self.find_similar_files(source_path)
                            self.issues.append(
                                Issue(
                                    file=rel_path,
                                    line_num=line_num,
                                    check_type=CheckType.SOURCE,
                                    message=f'Missing: {original_path}' + (f' → {source_path}' if original_path != source_path else ''),
                                    suggestion='Verify path exists or update reference',
                                    similar_files=similar,
                                )
                            )
            except OSError as error:
                self.note_unreadable(file_path, error)
                continue
            except UnicodeDecodeError:
                # Not a failure to read. The bytes arrived and are not text, so
                # there is no reference in them to miss, and reporting every
                # binary file is the noise that stops the real findings landing.
                continue

    def check_script_references(self):
        """Check that bash script references point to existing files."""
        # The lookbehind stops the trailing "sh" of a preceding filename from
        # matching: in `for f in functions.sh aliases.sh`, "sh aliases.sh" would
        # otherwise read as an invocation of a script that was never referenced.
        script_pattern = re.compile(r'(?<![\w.-])(?:bash|sh)\s+["\']?([^\s"\']+\.sh)["\']?')

        for file_path in self.reference_check_files():
            try:
                rel_path = file_path.relative_to(self.root_dir)
                with file_path.open(encoding='utf-8') as f:
                    for line_num, line in self.lines_a_shell_could_run(file_path, f):
                        if 'bash' not in line and 'sh' not in line:
                            continue

                        if self.runs_on_another_host(line):
                            continue

                        documentation = self.documents_rather_than_runs(line, file_path)

                        for match in script_pattern.finditer(line):
                            script_path = match.group(1).rstrip('"\'')

                            if not script_path or self.is_dynamic_path(script_path):
                                continue

                            if documentation and self.names_a_placeholder(script_path):
                                continue

                            if documentation and self.describes_another_tree(script_path):
                                continue

                            resolved = self.anchor(script_path)

                            if not resolved.exists():
                                similar = self.find_similar_files(script_path)
                                self.issues.append(
                                    Issue(
                                        file=rel_path,
                                        line_num=line_num,
                                        check_type=CheckType.SCRIPT,
                                        message=f'Missing: {script_path}',
                                        suggestion='Verify script exists or update reference',
                                        similar_files=similar,
                                    )
                                )
            except OSError as error:
                self.note_unreadable(file_path, error)
                continue
            except UnicodeDecodeError:
                # Not a failure to read. The bytes arrived and are not text, so
                # there is no reference in them to miss, and reporting every
                # binary file is the noise that stops the real findings landing.
                continue

    def check_relative_path_fragility(self):
        """Check if relative paths are fragile to working directory changes."""
        source_pattern = re.compile(r'source\s+(?:["\']([^"\']+)["\']|([^\s]+))')

        for file_path in self.find_files('.sh'):
            try:
                rel_path = file_path.relative_to(self.root_dir)

                with file_path.open(encoding='utf-8') as f:
                    for line_num, line in enumerate(f, 1):
                        if 'source' not in line:
                            continue

                        match = source_pattern.search(line)
                        if not match:
                            continue

                        source_path = match.group(1) or match.group(2)
                        if not source_path:
                            continue

                        # A commented `source` has no working directory to be
                        # fragile about. Broken-reference errors still scan
                        # comments, because a stale path in a usage example is
                        # exactly the drift this tool exists to catch.
                        if line.strip().startswith('#'):
                            continue

                        if '$' in source_path or source_path.startswith('/') or self.is_dynamic_path(source_path):
                            continue

                        test_dirs = [
                            self.root_dir,
                            file_path.parent,
                            file_path.parent.parent,
                        ]

                        valid_from = []
                        for test_dir in test_dirs:
                            resolved = test_dir / source_path
                            if resolved.exists():
                                valid_from.append(test_dir)

                        if 0 < len(valid_from) < len(test_dirs):
                            try:
                                valid_desc = ', '.join(
                                    str(d.relative_to(self.root_dir)) if d != self.root_dir else 'repo root' for d in valid_from
                                )
                            except ValueError:
                                valid_desc = ', '.join(str(d) for d in valid_from)

                            self.warnings.append(
                                Warning(
                                    file=rel_path,
                                    line_num=line_num,
                                    check_type=CheckType.FRAGILE_CWD,
                                    message=f'Relative path only valid from: {valid_desc}',
                                    suggestion='Use absolute path or root directory variable',
                                )
                            )
            except OSError as error:
                self.note_unreadable(file_path, error)
                continue
            except UnicodeDecodeError:
                # Not a failure to read. The bytes arrived and are not text, so
                # there is no reference in them to miss, and reporting every
                # binary file is the noise that stops the real findings landing.
                continue

    def check_relative_traversal(self):
        """Detect relative directory traversal patterns fragile to file moves."""
        traversal_pattern = re.compile(r'([A-Z_]+_DIR)=.*\$\(cd.*\.\./.*pwd\)')

        for file_path in self.find_files('.sh'):
            try:
                rel_path = file_path.relative_to(self.root_dir)

                with file_path.open(encoding='utf-8') as f:
                    for line_num, line in enumerate(f, 1):
                        match = traversal_pattern.search(line)
                        if not match:
                            continue

                        var_name = match.group(1)

                        self.warnings.append(
                            Warning(
                                file=rel_path,
                                line_num=line_num,
                                check_type=CheckType.FRAGILE_REFACTOR,
                                message=(f'{var_name} uses relative directory traversal (../) - fragile to file moves'),
                                suggestion=('Consider dynamic root detection: git rev-parse --show-toplevel'),
                            )
                        )
            except OSError as error:
                self.note_unreadable(file_path, error)
                continue
            except UnicodeDecodeError:
                # Not a failure to read. The bytes arrived and are not text, so
                # there is no reference in them to miss, and reporting every
                # binary file is the noise that stops the real findings landing.
                continue

    def run_all_checks(self):
        """Run all validation checks."""
        self.load_rules()
        self.check_source_statements()
        self.check_script_references()

        if self.warn_fragile:
            self.check_relative_path_fragility()
            self.check_relative_traversal()

    def get_rules_path(self) -> Path | None:
        """Get rules file path."""
        return self._rules_path
